version: '3.8'
services:
  predict-server:
    build: ./backend
    ports:
      - "8099:8099"
    networks:
      - image-story-network
  website:
    build: ./website
    ports:
      - "80:80"
    depends_on:
      - predict-server
    networks:
      - image-story-network
networks:
  image-story-network:
    driver: bridge